<?php
// ------------------------------------------------------------
// index_auth_request_handler.php
// ------------------------------------------------------------
// Handles all user-auth actions for index page:
// - logout_user
// - create_account
// - sign_in
//
// This file only handles auth concerns.
// Booking concerns are handled in index_booking_request_handler.php.
$authAction = $_POST['action'] ?? '';

// 1) Logout: clear user session and redirect.
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $authAction === 'logout_user') {
    if (!index_page_has_valid_csrf_token()) {
        $errors[] = 'Invalid request token. Please try again.';
    } else {
        unset($_SESSION['user_id'], $_SESSION['username']);
        index_page_set_flash_message('auth', 'You have been signed out.');
        header('Location: ' . $_SERVER['PHP_SELF']);
        exit;
    }
}

// 2) Create account flow.
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $authAction === 'create_account') {
    $authMode = 'create';

    if (!index_page_has_valid_csrf_token()) {
        $authErrors[] = 'Invalid request token. Please refresh and try again.';
    } else {
        // Read submitted credentials.
        $username = trim($_POST['username'] ?? '');
        $password = $_POST['password'] ?? '';

        if ($username === '' || $password === '') {
            $authErrors[] = 'Username and password are required.';
        }

        if (strlen($username) < 3) {
            $authErrors[] = 'Username must be at least 3 characters.';
        }

        if (strlen($password) < 6) {
            $authErrors[] = 'Password must be at least 6 characters.';
        }

        if (!$authErrors) {
            // Make sure username is not already used.
            $existsStmt = $conn->prepare('SELECT id FROM users WHERE username = ? LIMIT 1');
            $existsStmt->bind_param('s', $username);
            $existsStmt->execute();
            $existsRow = $existsStmt->get_result()->fetch_assoc();
            $existsStmt->close();

            if ($existsRow) {
                $authErrors[] = 'That username is already taken.';
            }
        }

        if (!$authErrors) {
            // Never store plain passwords.
            // Store only a secure hash generated by PHP.
            $passwordHash = password_hash($password, PASSWORD_DEFAULT);
            $createStmt = $conn->prepare('INSERT INTO users (username, password_hash) VALUES (?, ?)');
            $createStmt->bind_param('ss', $username, $passwordHash);

            if ($createStmt->execute()) {
                $_SESSION['user_id'] = (int)$createStmt->insert_id;
                $_SESSION['username'] = $username;
                index_page_set_flash_message('booking', 'Account created successfully. Welcome!');
                header('Location: ' . $_SERVER['PHP_SELF']);
                exit;
            }

            $authErrors[] = 'Unable to create account right now. Please try again.';
            $createStmt->close();
        }
    }
}

// 3) Sign-in flow for existing users.
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $authAction === 'sign_in') {
    $authMode = 'signin';

    if (!index_page_has_valid_csrf_token()) {
        $authErrors[] = 'Invalid request token. Please refresh and try again.';
    } else {
        // Read submitted credentials.
        $username = trim($_POST['username'] ?? '');
        $password = $_POST['password'] ?? '';

        if ($username === '' || $password === '') {
            $authErrors[] = 'Username and password are required.';
        } else {
            // Fetch user by username, then verify password hash.
            $signInStmt = $conn->prepare('SELECT id, username, password_hash FROM users WHERE username = ? LIMIT 1');
            $signInStmt->bind_param('s', $username);
            $signInStmt->execute();
            $userRow = $signInStmt->get_result()->fetch_assoc();
            $signInStmt->close();

            if ($userRow && password_verify($password, $userRow['password_hash'])) {
                session_regenerate_id(true);
                $_SESSION['user_id'] = (int)$userRow['id'];
                $_SESSION['username'] = $userRow['username'];
                index_page_set_flash_message('booking', 'Signed in successfully.');
                header('Location: ' . $_SERVER['PHP_SELF']);
                exit;
            }

            $authErrors[] = 'Invalid username or password.';
        }
    }
}
